<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Infrastructure/TaskHub.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Application/TaskHub.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="../Application/TaskHub.Modules.Tasks.Application.csproj" />
    <ProjectReference Include="../Domain/TaskHub.Modules.Tasks.Domain.csproj" />
  </ItemGroup>
</Project>
